<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Payment Report</title>
    <style>
        body {
            font-family: sans-serif;
            font-size: 12px;
            margin: 0;
            padding: 0;
        }

        .header {
            text-align: center;
            border-bottom: 2px solid #000;
            padding-bottom: 10px;
            margin-bottom: 15px;
        }

        .header h1 {
            margin: 0;
            font-size: 20px;
            text-transform: uppercase;
            font-weight: bold;
        }

        .header p {
            margin: 2px 0;
            font-size: 12px;
        }

        .report-title {
            text-align: center;
            margin: 10px 0 20px;
            font-size: 16px;
            font-weight: bold;
            text-decoration: underline;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        th,
        td {
            border: 1px solid #333;
            padding: 6px;
            vertical-align: top;
        }

        th {
            background-color: #f0f0f0;
            font-weight: bold;
        }

        .footer {
            position: fixed;
            bottom: 15px;
            left: 0;
            right: 0;
            text-align: center;
            font-size: 11px;
            color: #555;
        }
    </style>
</head>

<body>

    <!-- Header -->
    <div class="header">
        <h1>SKM AND COMPANY</h1>
        <p>32/1, Adhi Selvan Street, Ammapet, Salem - 636 003</p>
    </div>

    <!-- Report Title and Date Range -->
    <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 15px;">
        <!-- Payment Report Title (Centered) -->
        <div style="flex-grow: 1; text-align: center; font-size: 16px; font-weight: bold; text-decoration: underline;">
            Payment Report
        </div>

        <!-- Generated Range (Left Aligned) -->
        <div style="font-size: 12px;">
            <strong>Generated Range:</strong> {{ $dateRange }}
            <br>
            <strong>Generated By:</strong> {{ auth()->user()->name ?? 'Unknown User' }}
        </div>
    </div>

    <!-- Report Table -->
    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Invoice No</th>
                <th> Invoice Date</th>
                <th> Company name</th>
                <th>Total Amount</th>
                <th>Pending Amount</th>
                <th>Status</th>
                <th>Payment Date(s)</th>
                <th>Amount Paid(s)</th>
                <th>Payment Method(s)</th>
                <th>Reference Number(s)</th>
            </tr>
        </thead>
        <tbody>
            @if ($payments->isEmpty())
                <tr>
                    <td colspan="9" style="text-align: center;">No payments found</td>
                </tr>
            @else
                @foreach ($payments as $index => $payment)
                    <tr>
                        <td>{{ $index + 1 }}</td>
                        <td>{{ $payment->invoice->invoice_no ?? 'N/A' }}</td>
                        <td>{{ \Carbon\Carbon::parse($payment->invoice->invoice_date)->format('d-m-Y') ?? 'N/A' }}</td>
                        <td>{{ $payment->invoice->customer->company_name ?? 'N/A' }}</td>
                        <td>{{ number_format($payment->total_amount, 2) }}</td>

                        <!-- Dynamically calculated Pending Amount -->
                        <td>{{ number_format($payment->pending_amount, 2) }}</td>

                        <td>{{ ucfirst($payment->status) }}</td>

                        <!-- Payment Dates -->
                        <td>
                            @if ($payment->paymentItems && $payment->paymentItems->isNotEmpty())
                                @foreach ($payment->paymentItems as $paymentItem)
                                    {{ \Carbon\Carbon::parse($paymentItem->payment_date)->format('d-m-Y') }}<br>
                                @endforeach
                            @else
                                N/A
                            @endif
                        </td>

                        <!-- Amount Paids -->
                        <td>
                            @if ($payment->paymentItems && $payment->paymentItems->isNotEmpty())
                                @foreach ($payment->paymentItems as $paymentItem)
                                    {{ number_format($paymentItem->amount, 2) }}<br>
                                @endforeach
                            @else
                                N/A
                            @endif
                        </td>

                        <!-- Payment Methods -->
                        <td>
                            @if ($payment->paymentItems && $payment->paymentItems->isNotEmpty())
                                @foreach ($payment->paymentItems as $paymentItem)
                                    {{ ucfirst($paymentItem->payment_method) }}<br>
                                @endforeach
                            @else
                                N/A
                            @endif
                        </td>

                        <!-- Reference Numbers -->
                        <td>
                            @if ($payment->paymentItems && $payment->paymentItems->isNotEmpty())
                                @foreach ($payment->paymentItems as $paymentItem)
                                    {{ $paymentItem->reference_number }}<br>
                                @endforeach
                            @else
                                N/A
                            @endif
                        </td>

                    </tr>
                @endforeach


            @endif
        </tbody>
    </table>

    <!-- Footer -->
    <div style="text-align: right; position: fixed; bottom: -30px; right: 0px;">
        Report Generated On: {{ \Carbon\Carbon::now()->format('d-m-Y h:i A') }}
    </div>
</body>

</html>
