<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Purchase Report</title>
    <style>
        body {
            font-family: sans-serif;
            font-size: 12px;
            margin: 0;
            padding: 0;
        }

        .header {
            text-align: center;
            border-bottom: 2px solid #000;
            padding-bottom: 10px;
            margin-bottom: 15px;
        }

        .header h1 {
            margin: 0;
            font-size: 20px;
            text-transform: uppercase;
            font-weight: bold;
        }

        .header p {
            margin: 2px 0;
            font-size: 12px;
        }

        .report-title {
            text-align: center;
            margin: 10px 0 20px;
            font-size: 16px;
            font-weight: bold;
            text-decoration: underline;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        th,
        td {
            border: 1px solid #333;
            padding: 6px;
            vertical-align: top;
        }

        th {
            background-color: #f0f0f0;
            font-weight: bold;
        }

        .footer {
            position: fixed;
            bottom: 15px;
            left: 0;
            right: 0;
            text-align: center;
            font-size: 11px;
            color: #555;
        }
    </style>
</head>

<body>

    <!-- Header -->
    <div class="header">
        <h1>SKM AND COMPANY</h1>
        <p>32/1, Adhi Selvan Street, Ammapet, Salem - 636 003</p>
    </div>

    <!-- Report Title and Date Range -->
    <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 15px;">
        <!-- Purchase Report Title (Centered) -->
        <div style="flex-grow: 1; text-align: center; font-size: 16px; font-weight: bold; text-decoration: underline;">
            Purchase Report
        </div>

        <!-- Generated Range (Left Aligned) -->
        <div style="font-size: 12px;">
            <strong>Generated Range:</strong> {{ $dateRange }}
            <br>
            <strong>Generated By:</strong> {{ auth()->user()->name ?? 'Unknown User' }}
        </div>
    </div>

    <!-- Report Table -->
    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Invoice No</th>
                <th>Invoice Date</th>
                <th>Supplier Name</th>
                <th>Sub Total</th>
                <th>CGST</th>
                <th>SGST</th>
                <th>IGST</th>
                <th>GST</th>
                <th>Total</th>
            </tr>
        </thead>
        <tbody>
            @if ($purchases->isEmpty())
                <tr>
                    <td colspan="10" style="text-align: center;">No purchases found</td>
                </tr>
            @else
                @foreach ($purchases as $index => $purchase)
                    <tr>
                        <td>{{ $index + 1 }}</td>
                        <td>{{ $purchase->invoice_no }}</td>
                        <td>{{ \Carbon\Carbon::parse($purchase->invoice_date)->format('d-m-Y') }}</td>
                        <td>{{ $purchase->supplier->name ?? 'N/A' }}</td>
                        <td>{{ number_format($purchase->sub_total, 2) }}</td>
                        <td>{{ number_format($purchase->cgst, 2) }}</td>
                        <td>{{ number_format($purchase->sgst, 2) }}</td>
                        <td>{{ number_format($purchase->igst, 2) }}</td>
                        <td>{{ number_format($purchase->gst, 2) }}</td>
                        <td>{{ number_format($purchase->total, 2) }}</td>
                    </tr>
                @endforeach
            @endif
        </tbody>
    </table>

    <!-- Footer -->
    <div style="text-align: right; position: fixed; bottom: -30px; right: 0px;">
        Report Generated On: {{ \Carbon\Carbon::now()->format('d-m-Y h:i A') }}
    </div>
</body>

</html>
