<!DOCTYPE html>
<html>
<head>
    <title>Quotation PDF</title>
    <style>
        body { font-family: Arial, sans-serif; }
        .header { text-align: center; font-size: 18px; font-weight: bold; margin-bottom: 20px; }
        .table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        .table, .table th, .table td { border: 1px solid black; }
        .table th, .table td { padding: 8px; text-align: center; }
        .footer { margin-top: 20px; font-size: 12px; text-align: center; }
    </style>
</head>
<body>

    <div class="header">Quotation #{{ $quotation->quotation_code }}</div>
    <p><strong>Customer Name:</strong> {{ $quotation->customer->company_name }}</p>
    <p><strong>Address:</strong> {{ $quotation->customer->address }}</p>
    <p><strong>Contact:</strong> {{ $quotation->customer->contact }}</p>
    <p><strong>GST No:</strong> {{ $quotation->customer->gst_number }}</p>

    <p><strong>Date:</strong> {{ $quotation->quotation_date }}</p>

    <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>Product</th>
                <th>Quantity</th>
                <th>Unit Price</th>
                <th>CGST</th>
                <th>SGST</th>
                <th>IGST</th>
                <th>Total</th>
            </tr>
        </thead>
        <tbody>
            @foreach($quotation->items as $index => $item)
            <tr>
                <td>{{ $index + 1 }}</td>
                <td>{{ $item->product->name }}</td>
                <td>{{ $item->quantity }}</td>
                <td>{{ number_format($item->unit_price, 2) }}</td>
                <td>{{ number_format($item->cgst, 2) }}</td>
                <td>{{ number_format($item->sgst, 2) }}</td>
                <td>{{ number_format($item->igst, 2) }}</td>
                <td>{{ number_format($item->total, 2) }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <p><strong>Subtotal:</strong> {{ number_format($quotation->sub_total, 2) }}</p>
    <p><strong>Total GST:</strong> {{ number_format($quotation->gst, 2) }}</p>
    <p><strong>Grand Total:</strong> {{ number_format($quotation->total, 2) }}</p>

    <div class="footer">
        Generated by ATMS | Date: {{ now()->format('Y-m-d H:i:s') }}
    </div>

</body>
</html>
